export const mockedUsersData = {
  users: {
    edges: [
      {
        node: {
          __typename: 'User',
          id: 92670,
          email: 'andrea.carrozzo@coverwallet.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '88de06b5-5b53-456b-b9ba-713e5bf90137',
          businesses: [
            { name: 'test business ', __typename: 'Business' },
            { name: 'Test Guy', __typename: 'Business' },
          ],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92932,
          email: 'vitali.kharevich@coverwallet.com',
          firstName: 'Vitali',
          fullName: 'Vitali Kharevich',
          lastName: 'Kharevich',
          phone: null,
          userRole: 'insured',
          uuid: 'b31e1485-459e-4447-80c8-e1441398a236',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92960,
          email: 'stfenix_tionlk460156@yopmail.com',
          firstName: 'Glen',
          fullName: 'Glen Quigley',
          lastName: 'Quigley',
          phone: '3648887750',
          userRole: 'insured',
          uuid: '61added6-c4b6-4cfc-a7d4-50f390667023',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92961,
          email: 'stfenix_tionva655475@yopmail.com',
          firstName: 'Vance',
          fullName: 'Vance Haag',
          lastName: 'Haag',
          phone: '3648887750',
          userRole: 'insured',
          uuid: 'c8016bbc-e2e8-4558-8935-c4b423d244e9',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92963,
          email: 'arianna.ronci@hiscox.com',
          firstName: 'arianna',
          fullName: 'arianna ronci',
          lastName: 'ronci',
          phone: '9142737496',
          userRole: 'insured',
          uuid: 'a16c35df-151d-495a-93cd-584c12c8499a',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92964,
          email: 'cw@cwtest.com',
          firstName: 'test',
          fullName: 'test test',
          lastName: 'test',
          phone: '8475651317',
          userRole: 'insured',
          uuid: '4169e1fe-88ba-42e2-96b0-acb187a10c8e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92965,
          email: 'smoketestcfvreg@cwtest.com',
          firstName: 'Smoketest FNL',
          fullName: 'Smoketest FNL DNF',
          lastName: 'DNF',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bAd2HAAS',
          businesses: [{ name: 'Smoketest FEGVETB', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92968,
          email: 'nameless_girl9569695@yopmail.com',
          firstName: 'Nameless Girl9569695',
          fullName: 'Nameless Girl9569695 LN',
          lastName: 'LN',
          phone: '3648887750',
          userRole: 'insured',
          uuid: '98628449-7441-416c-b673-12c0e3a1dc6c',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92969,
          email: 'nameless_girl5444721@yopmail.com',
          firstName: 'Nameless Girl5444721',
          fullName: 'Nameless Girl5444721 LN',
          lastName: 'LN',
          phone: '3648887750',
          userRole: 'insured',
          uuid: '6b03c131-1a75-44fa-85f5-e2e19639396e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92973,
          email: 'smoketestc2efd3@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bAedmAAC',
          businesses: [{ name: 'Smoketest wvrg2f', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92977,
          email: 'nameless_girl4756662@yopmail.com',
          firstName: 'Nameless Girl4756662',
          fullName: 'Nameless Girl4756662 LN',
          lastName: 'LN',
          phone: '3648887750',
          userRole: 'insured',
          uuid: '3a352379-75d1-41be-9aed-a15d0e2d2c9e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92981,
          email: 'smoketestdsvfv@cwtest.com',
          firstName: 'Smoketest efdvgfbv',
          fullName: 'Smoketest efdvgfbv cfdvtgfbt',
          lastName: 'cfdvtgfbt',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '6330b5b8-9511-4088-aad0-a3c93c2df95a',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 92993,
          email: 'mary.foster@cwtest.com',
          firstName: 'Mary',
          fullName: 'Mary Foster',
          lastName: 'Foster',
          phone: '2244444452',
          userRole: 'insured',
          uuid: '0031800000bAjA1AAK',
          businesses: [{ name: 'just because', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93008,
          email: 'edgar@coverwallet.com',
          firstName: 'Edgar',
          fullName: 'Edgar Cumbreras',
          lastName: 'Cumbreras',
          phone: '3479999999',
          userRole: 'CW_agent',
          uuid: '4f526700-54a4-49b7-aae1-d28e1356ca02',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93009,
          email: 'josep.m.mingot@coverwallet.com',
          firstName: 'josep',
          fullName: 'josep mingot',
          lastName: 'mingot',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'e7f9f983-6b4a-4975-b3cb-385ac8780d2d',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93010,
          email: 'pavel.drozd@coverwallet.com',
          firstName: 'Pavel',
          fullName: 'Pavel Drodz',
          lastName: 'Drodz',
          phone: '3479999999',
          userRole: 'CW_agent',
          uuid: '2c84f7c1-77e7-41f2-b5fe-4cce0fee474c',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93012,
          email: 'eric.yaffe@coverwallet.com',
          firstName: 'Eric',
          fullName: 'Eric Yaffe',
          lastName: 'Yaffe',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '352e023b-3e42-4bff-b6e3-4e399fb49605',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93013,
          email: 'luis.mata@coverwallet.com',
          firstName: 'Luis',
          fullName: 'Luis Mata',
          lastName: 'Mata',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '2a248e58-0a77-453b-b503-7b2d67c97b2a',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93021,
          email: 'smoketestcwdvwr@cwtest.com',
          firstName: 'Smoketest FNWKJ',
          fullName: 'Smoketest FNWKJ CNWVJW',
          lastName: 'CNWVJW',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '3af4f3c1-c12e-4ebb-bfab-f44f5a58719f',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93023,
          email: 'smoketestvfedbfb2@cwtest.com',
          firstName: 'Smoketest CDVR',
          fullName: 'Smoketest CDVR VFEVF',
          lastName: 'VFEVF',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '814b2d0f-cad5-49b1-b5a8-499c09a579d3',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93025,
          email: 'smoketestfdebefbre@cwtest.com',
          firstName: 'Smoketest FREV',
          fullName: 'Smoketest FREV CRVFE',
          lastName: 'CRVFE',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'df709721-0c6e-4311-8194-01b1904db625',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93027,
          email: 'smoketestsvfvfe@cwtest.com',
          firstName: 'Smoketest sfvfb',
          fullName: 'Smoketest sfvfb cfbef',
          lastName: 'cfbef',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '9b674e40-9d09-49ef-8651-3896fab136a9',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93028,
          email: 'smoketestdfbvgnbtr@cwtest.com',
          firstName: 'Smoketest FNR',
          fullName: 'Smoketest FNR VFRRVM',
          lastName: 'VFRRVM',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '83409601-a30a-4b14-838d-2d633f5cbe3d',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93030,
          email: 'smoketestefvfebef@cwtest.com',
          firstName: 'Smoketest dvfvwdvd',
          fullName: 'Smoketest dvfvwdvd rcdvrgfb',
          lastName: 'rcdvrgfb',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'c4364d1c-d876-445a-a411-d82ee3007cd6',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93033,
          email: 'smoketestcdavfv@cwtest.com',
          firstName: 'smoketest csdv',
          fullName: 'smoketest csdv cdvfd',
          lastName: 'cdvfd',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'f9f44aa7-b389-4897-be50-875760ac30ea',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93034,
          email: 'smoketest15aug819@cwtest.com',
          firstName: 'SmokeTest15Aug819',
          fullName: 'SmokeTest15Aug819 SmokeTest15Aug819',
          lastName: 'SmokeTest15Aug819',
          phone: '5164169021',
          userRole: 'insured',
          uuid: 'd3e958e0-792a-401b-b17d-7437da39db84',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93035,
          email: 'smoketest15aug823@cwtest.com',
          firstName: 'SmokeTest15aug823',
          fullName: 'SmokeTest15aug823 SmokeTest15aug823',
          lastName: 'SmokeTest15aug823',
          phone: '5164169021',
          userRole: 'insured',
          uuid: 'a17b10d2-51ee-4534-ae3f-3ac5f2eafea3',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93036,
          email: 'smoketestcdsvfb@cwtest.com',
          firstName: 'Smoketest tvsd',
          fullName: 'Smoketest tvsd cdvfwd',
          lastName: 'cdvfwd',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '5bae352d-0951-4350-91f6-6e75597aa1e7',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93037,
          email: 'smoketest15aug838@cwtest.com',
          firstName: 'Smoketest15aug838',
          fullName: 'Smoketest15aug838 Smoketest15aug838',
          lastName: 'Smoketest15aug838',
          phone: '5164169021',
          userRole: 'insured',
          uuid: 'a67115f0-bb12-485e-ab0c-60bc5f84f60b',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93038,
          email: 'smoketestvfsvfb@cwtest.com',
          firstName: 'Smoketes efb',
          fullName: 'Smoketes efb vfeb',
          lastName: 'vfeb',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '077a1733-1504-4111-8d4c-2e8ab97a22a6',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93040,
          email: 'smoketest15aug935@cwtest.com',
          firstName: 'SmokeTest15Aug935',
          fullName: 'SmokeTest15Aug935 SmokeTest15Aug935',
          lastName: 'SmokeTest15Aug935',
          phone: '5164169021',
          userRole: 'insured',
          uuid: '0930d3d3-b600-4d70-98ee-00a99565d10d',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93041,
          email: 'smoketest15aug938@cwtest.com',
          firstName: 'SmokeTest15Aug938',
          fullName: 'SmokeTest15Aug938 SmokeTest15Aug938',
          lastName: 'SmokeTest15Aug938',
          phone: '5164169021',
          userRole: 'insured',
          uuid: '02d104cb-64d1-4257-ae55-99cd87e683de',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93042,
          email: 'smoketestdgjkiffc@cwtest.com',
          firstName: 'Smoketest fn',
          fullName: 'Smoketest fn Ln',
          lastName: 'Ln',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '4d2bb8ac-843d-4743-920f-50439f9ffb46',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93043,
          email: 'smoketestfvfbt@cwtest.com',
          firstName: 'Smoketest fvgb ',
          fullName: 'Smoketest fvgb  drfegtbq',
          lastName: 'drfegtbq',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '5e6289d2-de0a-4ae2-af3b-ea08309ababc',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93044,
          email: 'smoketestjvgjghvj@cwtest.com',
          firstName: 'smoketest fn',
          fullName: 'smoketest fn ln',
          lastName: 'ln',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'f706107c-392a-4ec2-b2ac-b116d3d6041e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93045,
          email: 'smoketestjdjdj@cwtest.com',
          firstName: 'smokiest fn',
          fullName: 'smokiest fn ln',
          lastName: 'ln',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '3e4a87f3-fdf6-4bf0-a46f-ac771fc0812d',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93046,
          email: 'smoketestsdvfeb@cwtest.com',
          firstName: 'Smoketest frnrvg',
          fullName: 'Smoketest frnrvg cnvju',
          lastName: 'cnvju',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '6343d714-4aa1-44d4-9f6b-ce2b1cc80657',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93048,
          email: 'smoketestefvfbvr2d@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bAowUAAS',
          businesses: [{ name: 'Smoketest svr334', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93051,
          email: 'smoketestsdvfvftb@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '02cb7b47-3f13-4c6a-b42f-7cded0592e82',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93052,
          email: 'smoketestvfsnvbgb@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '518cf8ec-b333-4636-ba92-4b841bf48b2f',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93054,
          email: 'test@hiscox.com',
          firstName: 'Test',
          fullName: 'Test Test',
          lastName: 'Test',
          phone: '4044102800',
          userRole: 'insured',
          uuid: '003S000001SRtAxIAL',
          businesses: [
            { name: 'GA GL Company', __typename: 'Business' },
            { name: 'AL Test PL Policy', __typename: 'Business' },
            { name: 'clinical counselot', __typename: 'Business' },
            { name: 'Psychologist Company Policy', __typename: 'Business' },
            { name: 'Social Worker Policy', __typename: 'Business' },
            { name: 'NY GL Test Policy', __typename: 'Business' },
            { name: 'Testing combo policy', __typename: 'Business' },
          ],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93055,
          email: 'tes@hiscox.com',
          firstName: 'test',
          fullName: 'test test',
          lastName: 'test',
          phone: '6787814705',
          userRole: 'insured',
          uuid: '0926ab1b-3326-4895-b0a2-67de7c7e4f7e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93056,
          email: 'swing2004@gmail.com',
          firstName: 'When',
          fullName: 'When Did',
          lastName: 'Did',
          phone: '7578524568',
          userRole: 'insured',
          uuid: '4f2179b1-b991-4cb7-8af1-154f8853d233',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93057,
          email: 't@aol.com',
          firstName: 'test',
          fullName: 'test test',
          lastName: 'test',
          phone: '7702123156',
          userRole: 'insured',
          uuid: '2fcbf951-892b-4301-9e28-d3930deb9ed2',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93058,
          email: 'career2002@gmail.com',
          firstName: 'Life',
          fullName: 'Life Career',
          lastName: 'Career',
          phone: '7578524565',
          userRole: 'insured',
          uuid: 'b407ec9d-8cea-4b0c-b5d1-fde7d11bd020',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93059,
          email: 'post@gmail.com',
          firstName: 'Post',
          fullName: 'Post Post',
          lastName: 'Post',
          phone: '7578524568',
          userRole: 'insured',
          uuid: '0031800000cBTIaAAO',
          businesses: [{ name: 'Business Consulting', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93060,
          email: 'smoketestfvbgbt@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bAtv6AAC',
          businesses: [{ name: 'Smoketest sfcefvrf', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93065,
          email: 'francisco.alvarez@coverwallet.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'CW_agent',
          uuid: '0031800000eAMa5AAG',
          businesses: [
            {
              name: 'Smoketest Fran Account - QA BETA',
              __typename: 'Business',
            },
          ],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93086,
          email: 'smoketestrfvbtbr@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'f5a6b3ff-9e46-43e3-bc9c-1668c42593b4',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93088,
          email: 'smoketestfjfjs@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '09b8462e-30cd-4b06-82d3-d279a98155f7',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93092,
          email: 'smoketestat002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '273872e7-cf9f-44b3-9af4-7981982db6f6',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93093,
          email: 'smoketestat003@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '4d4a63cd-4be8-4726-9ad9-bdc5bb5135e1',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93097,
          email: 'carmen.llorente@coverwallet.com',
          firstName: 'carmen',
          fullName: 'carmen llorente',
          lastName: 'llorente',
          phone: '',
          userRole: 'CW_agent',
          uuid: '564a47f9-a3f9-467d-90c3-4c5054cfa038',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93098,
          email: 'maite.galan@coverwallet.com',
          firstName: 'maite',
          fullName: 'maite galan',
          lastName: 'galan',
          phone: null,
          userRole: 'CW_agent',
          uuid: 'e8c79ec0-e742-418f-9595-1618bc0c4823',
          businesses: [{ name: 'coverwallet', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93101,
          email: 'smoketestan002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'b9eea463-a566-45e3-85f5-becd52989962',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93103,
          email: 'testhugo@cwtest.com',
          firstName: 'TEST_HMC',
          fullName: 'TEST_HMC TEST_HMC_SURNAME',
          lastName: 'TEST_HMC_SURNAME',
          phone: '8123123221',
          userRole: 'insured',
          uuid: '0031800000bB4GtAAK',
          businesses: [{ name: 'TEST_HMC_MON1523', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93105,
          email: 'smoketestat008@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'e139f7bc-326c-4a94-b467-98c3f0dad8a9',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93106,
          email: 'smoketestad009@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bB4JEAA0',
          businesses: [{ name: 'Smoketest AD009', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93108,
          email: 'smoketestad012@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'd83bd686-f603-4bd6-a63f-8d026a6d8feb',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93111,
          email: 'smoketestad014@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'd84d9ba0-739f-4029-b44f-3548d660c5c2',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93113,
          email: 'smoketestrt002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '4f59b572-2401-4fec-99fe-44de90dc30b1',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93115,
          email: 'smoketestqe002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'fe0d1cb0-0967-4508-8d6d-8d0dbef237dc',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93116,
          email: 'smoketestqe003@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '68a4afd5-f076-45ea-95b8-65b9d812b479',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93118,
          email: 'smoketestar002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0d62c76d-72a9-4aef-a110-b2e66503f979',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93121,
          email: 'smoketestah002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'fe2e120b-3a72-411a-8b6a-372cb237f064',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93122,
          email: 'smoketestah004@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '80040d07-595b-4283-af58-26c2aabace26',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93125,
          email: 'smoketestah006@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '074492a5-6c6d-4067-b940-8d970403a975',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93126,
          email: 'smoketestah008@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'af4e90b0-c34d-400c-a09f-7cf106cabd64',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93128,
          email: 'smoketestll001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000bBA4hAAG',
          businesses: [{ name: 'Smoketest LL001', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93129,
          email: 'smoketestga002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'd0d4e8b6-f5b3-4b70-8d89-86512059e560',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93131,
          email: 'donotsmoke112@cwtest.com',
          firstName: 'DonotSmoketest',
          fullName: 'DonotSmoketest yousmokealottest',
          lastName: 'yousmokealottest',
          phone: '4012391293',
          userRole: 'insured',
          uuid: '398dd409-e248-4679-9849-a1fcf318634b',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93134,
          email: 'smoketestji002@cwtest.com',
          firstName: 'Smoketest JI002 FN',
          fullName: 'Smoketest JI002 FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '635048cd-1c8f-4758-aaa6-1d8947b6ab26',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93135,
          email: 'smoketestji004@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'c64818e8-bd11-41e7-92d1-74e919f23a4c',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93137,
          email: 'smoketestji006@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'c9225691-eaed-4f36-9db9-a61971216404',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93141,
          email: 'hugo_test_tue1852@cwtest.com',
          firstName: 'HUGO_TEST_TUE1852',
          fullName: 'HUGO_TEST_TUE1852 HUGO_TEST_TUE1852',
          lastName: 'HUGO_TEST_TUE1852',
          phone: '3478792542',
          userRole: 'insured',
          uuid: 'e558284e-e2cb-449d-a51e-6e355a1a0e8e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93156,
          email: 'smoketestadj002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'beb5e96a-71e0-4523-a52f-1e9fbf40d3e2',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93158,
          email: 'smoketestagg001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'd11f1c32-1abf-4e7c-bbce-269f600cade4',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93159,
          email: 'smoketestagg003@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '6f350626-49bc-4d04-88a6-de3fa59d25c7',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93161,
          email: 'smoketestall002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'be452c71-e1c8-457a-8030-1c7e5ae21aba',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93162,
          email: 'smoketestaoo001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'a4cf6b07-3f7a-4219-bcd4-58012ecb6fc3',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93163,
          email: 'smoketestaoo002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'e38a0bc0-589b-49e2-81d3-e390d4e7719c',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93165,
          email: 'jorge.garces@coverwallet.com',
          firstName: 'Frog',
          fullName: 'Frog King',
          lastName: 'King',
          phone: null,
          userRole: 'CW_agent',
          uuid: '449d00d8-af53-4895-b268-77ea538dd90f',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93166,
          email: 'smoketestgggow001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'bf9c7a27-7823-4f03-b748-96a22febb5ab',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93167,
          email: 'smoketestasd008@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'be52e072-732a-49ac-b5bc-f0f0cd66df82',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93168,
          email: 'hmctest@cwtest.com',
          firstName: 'HMCTEST',
          fullName: 'HMCTEST HMCTEST',
          lastName: 'HMCTEST',
          phone: '7077951636',
          userRole: 'insured',
          uuid: '4bcadaff-1e8d-4930-8979-d7987b42fc9e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93169,
          email: 'smoketestadcfdfv@cwtest.com',
          firstName: 'SMoketest FN',
          fullName: 'SMoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '8d7e49a9-c75d-431d-9f40-2c54adcbb966',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93170,
          email: 'smoketestsfdvfv@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '4aa92b04-f563-40ca-b3fa-88d2df79ddbe',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93171,
          email: 'smoketestdvfvrfbrrf@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '95819b7c-8043-483f-9680-6a1e6114fd75',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93172,
          email: 'smoketest_yy_1501@cwtest.com',
          firstName: 'yury',
          fullName: 'yury yaroshyk',
          lastName: 'yaroshyk',
          phone: '6469922123',
          userRole: 'insured',
          uuid: '1f31dacb-276a-49ea-b5fe-78e3696f4ba0',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93173,
          email: 'smoketestddd001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'ef50a8f4-76eb-445c-a0d1-8df4d02feecc',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93174,
          email: 'test@coverwallet.com',
          firstName: 'test',
          fullName: 'test test',
          lastName: 'test',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '41dead41-d67b-44d0-a0e3-336a840fe1dc',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93175,
          email: 'smoketestaqq008@cwtest.com',
          firstName: 'Smoketest FNL',
          fullName: 'Smoketest FNL LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000c8bnEAAQ',
          businesses: [{ name: 'Smoketest AQQ008', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93176,
          email: 'smoketestaqq010@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'fe7238b6-d8a0-4bc5-9441-067f7b639743',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93177,
          email: 'smoketestaqq015@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '0031800000c8btOAAQ',
          businesses: [{ name: 'Smoketest AQQ016', __typename: 'Business' }],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93178,
          email: 'smoketestaqq011@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'd8da34d4-ea90-44fc-8305-cced8b345776',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93179,
          email: 'smoketestaqq021@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'a5c6991c-3054-43ab-bf73-2450cd666246',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93181,
          email: 'smoketestasq001@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '682def70-0f2d-4980-91ed-d6122697193c',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93183,
          email: 'smoketestsqq002@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '21fad347-154c-4ca4-b0d0-2e977e1b481f',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93185,
          email: 'smoketestadd034@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: '2546a3c6-7b55-47fe-aa03-07dcaa2d3316',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
      {
        node: {
          __typename: 'User',
          id: 93187,
          email: 'smoketestzqq003@cwtest.com',
          firstName: 'Smoketest FN',
          fullName: 'Smoketest FN LN',
          lastName: 'LN',
          phone: '3479999999',
          userRole: 'insured',
          uuid: 'e2915312-7b9d-44b6-ae84-dc905fdcb37e',
          businesses: [],
        },
        __typename: 'UserEdge',
      },
    ],
    pageInfo: {
      endCursor: 'MTAw',
      hasNextPage: true,
      __typename: 'PageInfo',
    },
    __typename: 'UserConnection',
  },
};
